### ISSUE TITLE
Great!I still want the latex code,can you share it?

### ISSUE THREAD

**Issue by BlackTea-c** [ZhaoPeiduo/DSML-Materials#5]
I want to change some points :3   🥰

**Comment by ZhaoPeiduo** [comment]
Please kindly drop an email and I will share the latex code :) I will not be publishing the latex source code here but only the pdfs

**Comment by ZhaoPeiduo** [comment]
And if you are currently taking this mod you can add me on wechat and I will add you to the group where I open-sourced the latex code

**Comment by BlackTea-c** [comment]
Got it! My email is 3626973771@qq.com. Actually, I'm already in this WeChat group.
and thanks again for your great kindness and dedication to this! 💕

**Comment by ZhaoPeiduo** [comment]
No problem, and I will update the code in the group as soon as I catch a break (current version is pinned on noticeboard)... Apologies that I wish to seek a balance between copyright issues and trusting people to make their own customizations over what I have :") Atb for all your mods in this semester!
